src/Entity/Ad.php
<?php
namespace App\Entity;
use Cocur\Slugify\Slugify;
use App\Repository\AdRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
/**
 * @ORM\Entity(repositoryClass=AdRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *  fields={"title"},
 *  message="Une autre annonce posséde déjà ce titre, merci de le modifier"
 * )
 */
class Ad
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255, minMessage="Le titre doit faire plus de 10 caractères", maxMessage="Le titre ne doit pas faire plus de 255 caractères")
     */
    private $title;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;
    /**
     * @ORM\Column(type="float")
     */
    private $price;
    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20, minMessage="Votre introduction doit faire plus de 20 caractères")
     */
    private $introduction;
    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="Votre description doit faire plus de 100 caractères")
     */
    private $content;
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url()
     */
    private $coverImage;
    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;
    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="ads")
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="ad")
     */
    private $comments;


    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le slug automatiquement
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * Permet de récupérer la note d'une annonce
     */
    public function getAvgRatings()
    {
        /* Calculer la somme des notations
         * La fonction php array_reduce permet de réduire le tableau à une seule valeur (attention il faut un tableau
         * pas une arrat Collection, on va utiliser toArray() - 2ème paramètre c'est la fonction pour chaque valeur,
         * 3ème paramètre valeur par defaut)
         */
        $sum = array_reduce($this->comments->toArray(), function($total, $comment){
            return $total + $comment->getRating();
        },0);

        // faire la division pour avoir la moyenne (ternaire)
        if (count($this->comments) > 0) return $moyenne = round($sum / count($this->comments));

        return 0;
    }

    /**
     * Permet de récupérer le commentaire d'un auteur par rapport à une annonce
     */
    public function getCommentFromAuthor(User $author)
    {
        foreach($this->comments as $comment) {
            if ($comment->getAuthor() === $author ) return $comment;
        }

        return null;
    }

    /**
     * Permet d'obtenir un tableau des jours qui ne sont pas disponibles pour cette annonce
     */
    public function getNotAvailableDays()
    {
        $notAvailableDays = [];
        foreach($this->bookings as $booking) {
            // calculer les jours qui se trouvent entre la date d'arrivée et de départ
            // la function range() de php permet de créer un tableau qui contient chaque étape existante entre deux nombres
            // $result = range(10,20,2)
            // réponse: $resultat = [10,12,14,16,18,20]
            $resultat = range($booking->getStartDate()->getTimestamp(), $booking->getEndDate()->getTimestamp(), 24*60*60);
            $days = array_map(function($dayTimestamp){
                return new \DateTime(date('Y-m-d',$dayTimestamp));
            }, $resultat);
            $notAvailableDays = array_merge($notAvailableDays,$days);
        }
        return $notAvailableDays;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;
        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;
        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;
        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;
        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;
        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;
        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Image;
use App\Form\AnnonceType;
use App\Repository\AdRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AdController extends AbstractController
{
    /**
     * @Route("/ads", name="ads_index")
     */
    public function index(AdRepository $repo): Response
    {
        $ads = $repo->findAll();

        return $this->render('ad/index.html.twig', [
            'ads' => $ads,
        ]);
    }

    /**
     * Permet de créer une annonce
     * @Route("/ads/new", name="ads_create")
     */
    public function create(Request $request, EntityManagerInterface $manager): Response
    {
        $ad = new Ad();

        $form = $this->createForm(AnnonceType::class, $ad);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            foreach ($ad->getImages() as $image) {
                $image->setAd($ad);
                $manager->persist($image);
            }

            // on ajoute l'auteur mais attention risque de bug jusqu'à security
            $ad->setAuthor($this->getUser());

            $manager->persist($ad);
            $manager->flush();

            $this->addFlash(
                'success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a bien été enregistrée !"
            );

            return $this->redirectToRoute('ads_show', ['slug' => $ad->getSlug()]);
        }

        return $this->render("ad/new.html.twig", [
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet de modifier une annonce
     * @Route("/ads/{slug}/edit", name="ads_edit")
     * @Security("( is_granted('ROLE_USER') and user === ad.getAuthor() ) or is_granted('ROLE_ADMIN')", message="Cette annonce ne vous appartient pas, vous ne pouvez pas la modifier" )
     */
    public function edit(Request $request, EntityManagerInterface $manager, Ad $ad): Response
    {
        $form = $this->createForm(AnnonceType::class, $ad);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            foreach($ad->getImages() as $image) {
                $image->setAd($ad);
                $manager->persist($image);
            }

            $manager->persist($ad);
            $manager->flush();

            $this->addFlash(
                'success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a bien été modifiée !"
            );
        }

        return $this->render("ad/edit.html.twig", [
            "form" => $form->createView(),
            'ad' => $ad
        ]);
    }

    /**
     * Permet de supprimer une annonce
     * @Route("/ads/{slug}/delete", name="ads_delete")
     * @Security("( is_granted('ROLE_USER') and user === ad.getAuthor() ) or is_granted('ROLE_ADMIN')",
     *      message="Cette annonce ne vous appartient pas, vous ne pouvez pas l'effacer")
     */
    public function delete(Ad $ad, EntityManagerInterface $manager)
    {
        $this->addFlash(
            'success',
            "L'annonce <strong>{$ad->getTitle()}</strong> a bien été supprimée"
        );

        $manager->remove($ad);
        $manager->flush();

        return $this->redirectToRoute('ads_index');
    }

    /**
     * Permet d'afficher une seule annonce
     * @Route("/ads/{slug}", name="ads_show")
     */
    public function show($slug, Ad $ad): Response
    {
        return $this->render('ad/show.html.twig', [
            'ad' => $ad
        ]);
    }
}

templates/ad/_ad.html.twig
{% set url = path('ads_show', {'slug':ad.slug}) %}
<div class="col-md-4">
    <div class="card-header text-center">
        {{ ad.rooms }} chambres, <strong>{{ ad.price }} € / nuit</strong>
        <br>
        {% if ad.comments | length > 0 %}
            {% include "partials/rating.html.twig" with {'rating' : ad.avgRatings} %} ({{ ad.comments | length }} avis)
        {% else %}
            <small>Pas encore noté</small>
        {% endif %}
    </div>
    <a href="{{ url }}">
        <img src="{{ ad.coverImage }}" alt="image de l'annonce {{ ad.title }}" class="starsimg">
    </a>
    <div class="card-body">
        <h4 class="card-title">{{ ad.title }}</h4>
        <p class="card-text">{{ ad.introduction }}</p>
        <a href="{{ url }}" class="btn btn-secondary m-2">En savoir plus</a>
        {% if (app.user and app.user == ad.author) or is_granted('ROLE_ADMIN') %}
            <a href="{{ path('ads_edit', { 'slug': ad.slug }) }}" class="btn btn-warning m-2">Modification de l'annonce</a>
        {% endif %}
    </div>
</div>

templates/ad/_collection.html.twig
{% block _annonce_images_widget %}
    <p>Ici, vous pouvez ajouter vos propres images</p>
    {{ form_widget(form) }}
    <input type="hidden" id="widgets-counter" value="0">
    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">Ajouter une image</button>
    </div>
{% endblock %}

{% block _annonce_images_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _annonce_images_entry_widget %}
    <div class="form-group" id="block_{{ id }}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{ form_widget(form.url) }}
                        {{ form_errors(form.url) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.caption) }}
                        {{ form_errors(form.caption) }}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" class="btn btn-danger" data-action="delete" data-target="#block_{{ id }}">x
                </button>
            </div>
        </div>
    </div>
{% endblock %}

templates/ad/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}Modification de l'annonce : {{ ad.title }}{% endblock %}

{% form_theme form "ad/_collection.html.twig" %}

{% block body %}
    <div class="container">
        <h1>Modification de l'annonce : <strong>{{ ad.title }}</strong></h1>

        {{ form_start(form) }}
        {{ form_rest(form) }}
        <button type="submit" class="btn btn-primary mt-3">Modifier</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts %}
    <script src="/js/annonce.js"></script>
{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos annonces{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            {% for ad in ads %}
                {% include 'ad/_ad.html.twig' %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/ad/new.html.twig
{% extends "base.html.twig" %}

{% block title %}Création d'une annonce{% endblock %}

{% form_theme form _self %}

{% block body %}
    <div class="container">
        <h1>Création d'une nouvelle annonce</h1>

        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button type="submit" class="btn btn-primary mt-3">Création d'une annonce</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

{% block _annonce_images_widget %}
    {# définition du champ annonce_image, la variable form correspond au champ annonce_image #}
    <p>Ici, vous pouvez ajouter vos propres images</p>
    {{ form_widget(form) }}
    <input type="hidden" id="widgets-counter" value="0">
    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">Ajouter une image</button>
    </div>
{% endblock %}

{% block _annonce_images_entry_row %}
    {# entry précie le entry_type de notre AnnonceType au niveau de la collection - donc chaque formulaire ImageType #}
    {# permet de juste afficher le widget donc plus les 0 1 2 3 ect #}
    {{form_widget(form)}}
{% endblock %}

{% block _annonce_images_entry_widget %}
    <div class="form-group" id="block_{{ id }}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{ form_widget(form.url) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.caption) }}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" class="btn btn-danger" data-action="delete" data-target="#block_{{ id }}">x</button>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
<script>
    const addImage = document.querySelector('#add-image')

    addImage.addEventListener('click', () => {
        // compter combien j'ai de form-group pour les indices ex : annonce_image_0_url
        const widgetCounter = document.querySelector("#widgets-counter")
        const index = +widgetCounter.value // le + permet de transformer en nombre, value rends toujours un string
        const annonceImages = document.querySelector('#annonce_images')

        // recup le prototype des entrées data-prototype
        const prototype = annonceImages.dataset.prototype.replace(/__name__/g, index) // drapeau g pour indiquer que l'on va le faire plusieurs fois

        // injecter le code dans la div
        annonceImages.insertAdjacentHTML('beforeend', prototype)
        widgetCounter.value = index + 1

        handleDeleteButtons() // pour mettre à jour les tables delete et ajouter l'event
    })

    const updateCounter = () => {
        const count = document.querySelectorAll('#annonce_images div.form-group').length
        document.querySelector('#widgets-counter').value = count
    }

    const handleDeleteButtons = () => {
        var deletes = document.querySelectorAll("button[data-action='delete']")

        deletes.forEach(button => {
            button.addEventListener('click', () => {
                const target = button.dataset.target
                const elementTarget = document.querySelector(target)
                if (elementTarget) {
                    elementTarget.remove() // supprimer l'élément
                }
            })
        })
    }

    updateCounter()
    handleDeleteButtons()

</script>
{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonce: {{ ad.title }}{% endblock %}

{% block body %}
    <div class="annonce-title" style="background-image: url('{{ ad.coverImage }}')">
        <div class="container">
            <h1>{{ ad.title }}</h1>
            <p>{{ ad.introduction }}</p>
            <p class="h2"><strong>{{ ad.rooms }} chambres</strong> pour <strong>{{ ad.price }}</strong> € / nuit</p>
            <a href="{{ path("booking_create", { 'slug': ad.slug }) }}" class="btn btn-primary">Réserver</a>
            {# gestion de l'annonce #}
            {% if (app.user and app.user == ad.author) or is_granted('ROLE_ADMIN') %}
                <a href="{{ path('ads_edit', { 'slug': ad.slug }) }}" class="btn btn-warning mx-2">Modification de l'annonce</a>
                <a href="{{ path('ads_delete', { 'slug': ad.slug }) }}" class="btn btn-danger mx-2">Supprimer l'annonce</a>
            {% endif %}
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-8 mb-3">
                {{ ad.content | raw | nl2br }}
                <div class="bd-example">
                    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-indicators">
                            {% for image in ad.images %}
                                <button type="button" data-bs-target="#carouselExampleCaptions"
                                        data-bs-slide-to="{{ loop.index0 }}" {% if loop.first %} class="active" aria-current="true" {% endif %}
                                        aria-label="Slide {{ loop.index }}"></button>
                            {% endfor %}
                        </div>
                        <div class="carousel-inner">
                            {% for image in ad.images %}
                                <div class="carousel-item {% if loop.first %}active{% endif %}">
                                    <img src="{{ image.url }}" alt="image de {{ ad.title }}" class="d-block w-100">
                                    <div class="carousel-caption d-none d-md-block">
                                        <h5>{{ ad.title }}</h5>
                                        <p>{{ image.caption }}</p>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
                                data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="col">
                {% set a = ad.author %}
                <div class="row">
                    <div class="col-3">
                        <a href="{{ path('user_show', { 'slug': a.slug }) }}">
                            {% if a.picture %}
                                <img src="/uploads/{{ a.picture }}" alt="Avatar de {{ a.fullName }}" class="avatar avatar-medium">
                            {% else %}
                                <img src="http://placehold.it/300x300" alt="Avatar de {{ a.fullName }}" class="avatar avatar-medium">
                            {% endif %}
                        </a>
                    </div>
                    </div>
                    <div class="col">
                        <a href="{{ path('user_show', { 'slug': a.slug }) }}">
                            <h3>{{ a.fullName }}</h3>
                        </a>
                        <span class="badge bg-primary">Annonce(s) {{ a.ads | length }}</span>
                    </div>
                    {{ a.description | raw | nl2br }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script>
        var myCarousel = document.querySelector('#carouselExampleCaptions')
        var carousel = new bootstrap.Carousel(myCarousel)
    </script>
{% endblock %}